---
- name: Install dependencies for install
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - epel-release
    state: present

- name: Install pip
  package:
    name: python-pip
    state: present

- name: Install pyOpenSSL
  pip:
    name: pyOpenSSL>0.15
    state: present

- name: Add Docker's repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker packages
  yum:
    name:
      - "docker-ce-{{ docker_version }}*"
      - "docker-ce-cli-{{ docker_version }}*"
      - containerd.io
