---
- name: Install dependencies for install
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python-openssl
      - python-docker

- name: Add Docker's key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker's repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: Install docker packages
  apt:
    name:
      - "docker-ce={{ docker_debian_epoch }}:{{ docker_version }}*"
      - "docker-ce-cli={{ docker_debian_epoch }}:{{ docker_version }}*"
      - containerd.io
